<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="Keep your favorite NOVA finds close in your wishlist."><title>Your Wishlist — NOVA</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"><script src="js/products.js" defer></script><script src="js/script.js" defer></script></head>
<body data-page="wishlist"><div class="announcement">A little something extra: complimentary shipping on orders over $100 <a href="products.html">Explore the collection <span aria-hidden="true">↗</span></a></div><header class="site-header"><div class="header-main wrap"><button class="icon-button menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false">☰</button><a class="brand" href="index.html" aria-label="NOVA home">NOVA<span>.</span></a><nav class="primary-nav" aria-label="Main navigation"><a href="index.html">Home</a><a href="products.html">Shop</a><a href="products.html#categories">Categories</a><a href="index.html#story">Our story</a><a href="index.html#contact">Contact</a></nav><form class="header-search" role="search" action="products.html"><label class="sr-only" for="header-search">Search products</label><span aria-hidden="true">⌕</span><input id="header-search" name="q" type="search" placeholder="Find something lovely" autocomplete="off"></form><div class="header-actions"><a class="icon-button wishlist-link" href="wishlist.html" aria-label="Wishlist">♡<span class="count-badge wishlist-count">0</span></a><a class="icon-button cart-link" href="cart.html" aria-label="Shopping bag">♧<span class="count-badge cart-count">0</span></a></div></div></header>
<main class="wrap interior-page"><div class="breadcrumbs"><a href="index.html">Home</a><span>/</span><span>Your wishlist</span></div><div class="page-title-row"><div><p class="eyebrow">THE ONES YOU LOVE</p><h1>Your <em>wishlist.</em></h1></div><a class="text-link" href="products.html">← Keep browsing</a></div><div id="wishlist-content"></div></main>
<footer class="site-footer"><div class="wrap"><div class="footer-main"><div class="footer-brand"><a class="brand" href="index.html">NOVA<span>.</span></a><p>Thoughtful things for everyday living. Good design, better choices, and a little more joy in the ordinary.</p><div class="social-links"><a href="https://instagram.com" aria-label="Instagram">ig</a><a href="https://pinterest.com" aria-label="Pinterest">p</a><a href="https://tiktok.com" aria-label="TikTok">tk</a></div></div><div class="footer-column"><h2>Explore</h2><a href="products.html">Shop all</a><a href="products.html?category=Home">Home</a><a href="products.html?category=Fashion">Fashion</a><a href="products.html?category=Beauty">Beauty</a></div><div class="footer-column"><h2>Here to help</h2><a href="index.html#contact">Contact us</a><a href="cart.html">Shipping & returns</a><a href="wishlist.html">Your wishlist</a><a href="checkout.html">Checkout</a></div><div class="footer-column"><h2>The fine print</h2><a href="index.html#story">Our story</a><a href="index.html#contact">Privacy</a><a href="index.html#contact">Terms</a><p>Monday–Friday, 9–5 ET<br>hello@shopnova.example</p></div></div><div class="footer-bottom"><span>© 2025 NOVA Goods Co. Made for the everyday.</span><span>Thoughtfully found. <span aria-hidden="true">✳</span></span></div></div></footer><button class="back-to-top" type="button" aria-label="Back to top">↑</button><div class="toast-region" aria-live="polite" aria-atomic="true"></div></body></html>